#!/bin/bash
#SBATCH --job-name=cgc_cuda
#SBATCH --output=job_%j.out
#SBATCH --error=job_%j.err
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=defq
#SBATCH --gres=gpu:1
#SBATCH --time=00:30:00

# Load modules
module purge
module load gnu12/12.4.0
module load openmpi4/4.1.6
module load cuda12.1/toolkit/12.1

which mpirun


PROG=cgc_cuda

#DATA=/var/scratch/bwn200/HPC_data/spring_data_s.npy
#LABELS=/var/scratch/bwn200/HPC_data/spring_labels_s_3x20.txt

DATA=/var/scratch/bwn200/HPC_data/spring_data_m.npy
LABELS=/var/scratch/bwn200/HPC_data/spring_labels_m_5x100.txt


#DATA=/var/scratch/bwn200/HPC_data/spring_data_l.npy
#LABELS=/var/scratch/bwn200/HPC_data/spring_labels_l_5x100.txt


# Run mpirun
#mpirun ./${PROG} ${DATA} ${LABELS} -o ${OUT}

/usr/bin/time -p mpirun ./cgc_cuda $DATA $LABELS -o labels_m.txt
