#!/bin/bash
#SBATCH --job-name=cgc_cuda
#SBATCH --output=job_%j.out
#SBATCH --error=job_%j.err

#SBATCH --partition=defq

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1

#SBATCH --time=01:00:00

module purge
module load gnu12/12.4.0
module load openmpi4/4.1.6
module load cuda12.1/toolkit/12.1

export CUDA_VISIBLE_DEVICES=0

DATA=/var/scratch/bwn200/HPC_data/spring_data_xxl.npy
LABELS=/var/scratch/bwn200/HPC_data/spring_labels_xxl_5x100.txt

/usr/bin/time -p mpirun -np 1 ./cgc_cuda \
    $DATA \
    $LABELS \
    -o cuda_xxl.txt \
    -m 100